# Use the latest oraclelinux as the base image
FROM oraclelinux:9

# Set the working directory inside the container
WORKDIR /app

# Update package lists and install necessary dependencies
RUN dnf update && dnf install bash curl sudo -y

# Copy the script into the container
COPY main.sh /app/main.sh

# Grant execution permissions to the script
RUN chmod +x /app/main.sh

# Execute the script during build
RUN /bin/bash /app/main.sh --install
