# Use the latest Windows Server Core image as the base
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Set the working directory inside the container
WORKDIR C:/app

# Copy hello.ps1 script into the container
COPY main.ps1 C:/app/main.ps1

# Run the hello.ps1 PowerShell script
CMD ["powershell", "-ExecutionPolicy", "Bypass", "-File", "C:/app/main.ps1"]
